config/routes.rb
Rails.application.routes.draw do
  resources :groups
  get 'groups/:id/new_member/', to: 'groups#new_member', as: "new_member"
  post '/groups/:id/new_member/', to: 'groups#create_member', as: "create_member"
  post '/groups/destroy_member/:id', to: 'groups#destroy_member', as: "destroy_member"
  post '/groups/:id/update_member/', to:'groups#update_member', as: "update_member" 

  resources :user_classes, except:[:destroy]
  get '/user_classes/:id/new_subclass/', to: 'user_classes#new_subclass', as: "new_subclass"
  post '/user_classes/:id/new_subclass/', to: 'user_classes#create_subclass', as: "create_subclass"
  get '/user_classes/:id/edit_subclass/', to:'user_classes#edit_subclass', as: "edit_subclass"
  post '/user_classes/:id/edit_subclass/', to:'user_classes#update_subclass', as: "update_subclass"
  
  resources :sessions, only:[:new, :create, :destroy]
  get "/login", to: "sessions#new", as: "login"
  post "/logout", to: "sessions#destroy", as: "logout"
  root 'sessions#new'

  resources :users
  resources :comments
  get 'comments/:id/show_comment/', to: 'comments#show_comment', as: "show_comment"
  get 'comments/:id/edit_comment/', to:'comments#edit_comment', as: "edit"

  resources :skills
  
  resources :tasks
  get '/tasks/:id/partipar', to: 'tasks#assign_new', as: 'new_assign'
  get '/tasks/:id/comentarios', to: 'tasks#show_comments', as: 'show_comments'
  post '/tasks/:id/partipar', to: 'tasks#assign', as: 'create_assign'
  post '/tasks/:id/increase_xp', to: 'tasks#increase_xp', as: 'increase_xp'
  post '/tasks/:id/increase_time', to: 'tasks#increase_time', as: 'increase_time'
end

app/models/task.rb
class Task < ApplicationRecord
    has_many :people_tasks
    has_many :users
    has_many :groups
    has_many :comments
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
    require 'date'
    def index
        #@tasks = Task.order :id
        @tasks = Task.all
    end
    
    def new
        #New e create para criarmos uma tarefa (Não precisamos selecionar usuários aqui ainda)
        @task = Task.new()
    end

    def create
        #New e create para criarmos uma tarefa (Não precisamos selecionar usuários aqui ainda)
        @task = Task.new(task_params)
        @task.status = "incompleto"
        @task.lider_id = current_user.id
        @task.prazo_atual = @task.prazo_base
        @task.xp_atual = @task.xp_base
        @task.moedas_atual = @task.moedas_base

        if @task.save
            redirect_to task_path(@task)
        else
            render 'new'
        end
    end

    def edit
        #Edit e update para alterarmos uma tarefa. (Aqui só podemos editar o título e a descrição)
        @task = Task.find(params[:id])
    end
    
    def update
        #Edit e update para alterarmos uma tarefa. (Aqui só podemos editar o título e a descrição)
        @task = Task.find(params[:id])
        if @task.update(task_params)
            redirect_to task_path(@task)
        else
            render 'edit'
        end        
    end

    def destroy
        #Destroy para apagarmos uma tarefa (cuidado aqui, apenas o usuário que criou a tarefa pode apagá-la)  
        @task = Task.find(params[:id])
        @people_tasks = PeopleTask.where(task_id: params[:id])
        @comments = Comment.where(task_id: params[:id])

        @comments.destroy_all
        @people_tasks.destroy_all
        @task.destroy
        redirect_to tasks_path
    end

    def show
        #aqui poderemos visualizar os dados da tarefa e teremos um botão de finalizar a tarefa, visível apenas para o criador da tarefa.
        @task = Task.find(params[:id])
        @users = User.all
        @groups = Group.all
        @people_tasks = PeopleTask.where(task_id: params[:id])

        #testar se ja passou metade do prazo
        @time = Time.current
        @time_start = @time - @task.created_at
        @time_end = @task.prazo_atual - @time
        if @time_start < @time_end
            @prazo = true
        else
            @prazo = false
        end
    end

    def show_comments 
        @comments = Comment.where(task_id: params[:id])
    end

    def assign_new
        @participant = PeopleTask.new()
        @task = Task.find(params[:id])
    end

    def assign
        #Vamos precisar de um método para adicionar um usuário ou um grupo à tarefa. Lembrem-se que criou a tarefa não está participando da tarefa, se ele for participar também deve ser adicionado.
        if params[:tipo_usuario] == 'user'
            @participant = PeopleTask.new(user_id: current_user.id, task_id: params[:id])
            if @participant.save
                redirect_to tasks_path
            else
                render '#assign_new'
            end
        else
            if User.find(current_user.id).member && User.find(current_user.id).member.lider == 'SIM'
                @participant = PeopleTask.new(group_id: current_user.member.group_id, task_id: params[:id])
                if @participant.save
                    redirect_to tasks_path
                else
                    render '#assign_new'
                end
            end
        end
    end

    def finish
        #vamos precisar também de um método que permita finalizar a tarefa.
        #Quando a tarefa for finalizada as moedas e xp devem ser distribuídos
        #igualmente entre os participantes, notem que se tiver um usuário e um 
        #grupo participante, a distribuição é feita 50% para o usuário e 50% para 
        #o grupo, depois os 50% que ficou para o grupo é distribuído igualmente 
        #entre os membros do grupo. No momento da distribuição deve ser verificado 
        #se um usuário tem xp suficiente para passar de nível.'
        #'Obs: Se a tarefa for finalizada fora do prazo fina, deve ter uma penalidade de 90% de xp e 100% de moedas.
    end

    def increase_xp        
        @task = Task.find(params[:id])
        @porcentagem = @task.aumento_xp + params[:xp].to_f
        @aumento_valor = @task.xp_atual + @task.xp_atual * params[:xp].to_f/100
        @task.update(aumento_xp: @porcentagem, xp_atual: @aumento_valor)
        redirect_to task_path(@task)
    end

    def increase_time
        @task = Task.find(params[:id])
        @aumento_porcentagem = params[:prazo].to_f
        @porcentagem = @task.aumento_prazo + @aumento_porcentagem
        @aumento_valor = @task.prazo_atual.to_f + (@task.prazo_base.to_f - @task.created_at.to_f)* params[:prazo].to_f/100

        case @aumento_porcentagem
            when 10
                @moedas = @task.moedas_atual*0.55 #penalidade de 45%
                @xp = @task.xp_atual*0.55
            when 20
                @moedas = @task.moedas_atual*0.4 #penalidade de 60%
                @xp = @task.xp_atual*0.4
            when 30
                @moedas = @task.moedas_atual*0.25 #penalidade de 75%
                @xp = @task.xp_atual*0.25
        end

        @task.update(aumento_prazo: @porcentagem, prazo_atual: Time.at(@aumento_valor), xp_atual:@xp, moedas_atual:@moedas)
        redirect_to task_path(@task)
    end

    private
      def task_params
        params.require(:task).permit(:titulo, :descricao, :user_id, :xp_base, :moedas_base, :status, :prazo_base, :created_at, :updated_at,:grupo)
      end
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/tasks/_form-tasks.html.erb
<div class="container w-25">
  <%= form_with model: @task, local: true do |f| %>
      <div class="form-group">
        <%= f.label :titulo, "Titulo:" %>
        <%= f.text_field :titulo, placeholder: "Digite o titulo", class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.label :descricao, "Descrição:" %>
        <%= f.text_field :descricao, placeholder: "Digite a descrição", class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.label :xp_base, "Pontuação:" %>
        <%= f.text_field :xp_base, placeholder: "Digite o xp recebido pela tarefa", class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.label :moedas_base, "Moedas:" %>
        <%= f.text_field :moedas_base, placeholder: "Digite a quantidade de moedas recebida como recompensa", class: "form-control" %>
      </div>
        <div class="form-group">
        <%= f.label :prazo_base, "Prazo:" %>
        <%= f.datetime_select :prazo_base, class: "form-control" %>
      </div>
      
      <%= f.submit "Confirmar", class: "btn btn-success"%>
  <%end%>
</div>

<% @task.errors.full_messages.each do |error| %>
  <p style = "color:red"><%= error %></p>
<% end %>

app/views/tasks/_form-timebuttons.html.erb
<%= form_with scope: :task, url: increase_time_path(@task), local: true do |f| %>
    <% case @task.aumento_prazo.to_i %>
        <% when 0 %>
            <%= f.button "10%", name: "prazo", value: 10, class: "btn btn-warning" %>
            <%= f.button "20%", name: "prazo", value: 20, class: "btn btn-warning" %>
            <%= f.button "30%", name: "prazo", value: 30, class: "btn btn-warning" %>
        <% when 10 %>
            <%= f.button "10%", name: "prazo", value: 10, class: "btn btn-warning" %>
            <%= f.button "20%", name: "prazo", value: 20, class: "btn btn-warning" %>
        <% when 20 %>
            <%= f.button "10%", name: "prazo", value: 10, class: "btn btn-warning" %>
        <% else %>
            <h3 class="text-danger">Limite do aumento de prazo alcançado</h3>
        <% end %>
<% end %>

app/views/tasks/_form-xpbuttons.html.erb
<%= form_with scope: :task, url: increase_xp_path(@task), local: true do |f| %>
    <% case @task.aumento_xp.to_i %>
        <% when 0 %>
            <%= f.button "50%", name: "xp", value: 50, class: "btn btn-success" %>
            <%= f.button "100%", name: "xp", value: 100, class: "btn btn-success" %>
            <%= f.button "120%", name: "xp", value: 120, class: "btn btn-success" %>
        <% when 50 %>
            <%= f.button "50%", name: "xp", value: 50, class: "btn btn-success" %>
            <%= f.button "100%", name: "xp", value: 100, class: "btn btn-success" %>
        <% when 100 %>
            <%= f.button "50%", name: "xp", value: 50, class: "btn btn-success" %>
        <% else %>
            <h3 class="text-danger">Limite do aumento de XP alcançado</h3>
        <% end %>
<% end %>

app/views/tasks/assign_new.html.erb
<%= render 'users/users-navbar'%>
<div class="container">
    <h1>Participar da tarefa <%= @task.titulo %></h1>
    <div class="container w-25">
        <%= form_with model: @people_task, url: create_assign_path, local: true do |f| %>
            <div class="form-group">
                <%= f.label :tipo_usuario, "Participar como:"%>
                <% if current_user.member && current_user.member.lider == 'SIM' %>
                    <%= f.select(:tipo_usuario, options_for_select([['Usuário', 'user'], ['Grupo', 'group']]))%>
                <% else %>
                    <%= f.select(:tipo_usuario, options_for_select([['Usuário', 'user']]))%>
                <% end %>
            </div>
            <%= f.submit "Participar", class: "btn btn-success" %>
        <% end %>
    </div>
</div>

app/views/tasks/edit.html.erb
<div class="container w-25">
    <h1>Editar Tarefa</h1>
    <%= form_with model: @task, local: true do |f| %>
        <div class="form-group">
            <%= f.label :titulo, "Titulo" %>
            <%= f.text_field :titulo, placeholder: "Digite o titulo", class: "form-control" %>
        </div>
        <div class="form-group">
            <%= f.label :descricao, "Descrição" %>
            <%= f.text_field :descricao, placeholder: "Digite a descrição", class: "form-control" %>
        </div>
        <%= f.submit "Editar", class: "btn btn-success" %>
    <% end %>
</div>

app/views/tasks/index.html.erb
<%= render 'users/users-navbar' %>
<div class="container mt-2">
    <div class="row justify-content-center">
        <h1>Tarefas</h1>
        <table class="table">
            <tr>
                <th>ID</th>
                <th>Título</th>
                <th colspan="7">Ações</th>
            </tr>
            <% @tasks.each do |t|%>
                <tr>
                    <td><%= t.id %></td>
                    <td><%= t.titulo %></td>
                    <td class="link"><%= link_to "Exibir", action: "show", id: t %></td>
                    <td class="link"><%= link_to "Editar", edit_task_path(t) %></td>
                    <td class="link"><%= link_to "Comentários", show_comments_path(t) %></td>
                    <% if current_user and current_user.id = t.lider_id  %>
                        <td class="link"><%= link_to "Destruir", t, method: :delete %></td>
                    <% end %>
                    <% if current_user%>
                        <td class="link"><%= link_to "Participar", new_assign_path(t) %></td>
                    <% end %>
                </tr>
            <%end%>
        </table>
        <%= link_to "Nova tarefa", {action: "new"}, class: "btn btn-primary" %>
        <%= link_to "Novo comentário", new_comment_path, class:"btn btn-secondary ml-5" %>
    </div>
</div>

app/views/tasks/new.html.erb
<% if current_user %>
    <h1>Criar Tarefa</h1>
    <%= render 'form-tasks' %>
<% else %>
    <div class="container">
        <h1 class="error">Usuário não autenticado!</h1>
        <div class="row justify-content-center">
            <%= link_to "Voltar", tasks_path, class:"btn btn-secondary mr-5" %>
            <%= link_to "Fazer Login", new_session_path, class: "btn btn-primary" %>
        </div>
    </div>
<% end %>

app/views/tasks/show.html.erb
<%= render 'users/users-navbar' %>
<h1><%= @task.titulo %></h1>
<div class="container">
    <ul class="list-group">
        <li class="list-group-item">Descricao: <%= @task.descricao %></li>
        <li class="list-group-item">Pontuação: <%= @task.xp_atual.round(2) %></li>
        <li class="list-group-item">Moedas: <%= @task.moedas_atual.round(2) %></li>
        <li class="list-group-item">Prazo: <%= @task.prazo_atual %></li>
    </ul>
    <h2 class="mt-2 mb-2">Participantes</h2>
    <ul class="list-group">
    <% @people_tasks.each do |p|%>
        <% if p.user_id != nil %>
            <li class="list-group-item">Usuário: <%= @users.find(p.user_id).nome %></li>
        <% elsif p.group_id != nil %>
            <li class="list-group-item">Grupo: <%= @groups.find(p.group_id).nome %></li>
        <% end %>
    <% end %>
    </ul>

    <h3 style="float:left">Aumentar XP da Tarefa:</h3>
    <% if @prazo %>
        <%= render 'form-xpbuttons' %>
    <% else %>
        <h3 class="text-danger">Limite de prazo excedido para aumento de XP</h3>
    <% end %>

    <br>

    <h3 style="float:left">Aumentar Prazo da Tarefa:</h3>
        <%= render 'form-timebuttons' %>

    <%= link_to "Início", tasks_path, class: "btn btn-secondary w-100 mb-4 mt-4" %>
</div>

app/views/tasks/show_comments.html.erb
<%= render 'users/users-navbar' %>
<div class="container w-50 mt-3">
    <% @comments.each do |c|%>
        <ul class="list-group mb-3">
            <li class="list-group-item">Usuário: <%= c.user.nome %></li>
            <li class="list-group-item">Comentário: <%= c.comentario %></li>
        </ul>
        <%= link_to "Destruir", c, method: :delete, class:"btn btn-primary mb-3" %>
        <%= link_to "Editar", edit_comment_path, class:"btn btn-primary mb-3" %>
    <%end%>
</div>