config/routes.rb
Rails.application.routes.draw do
  resources :groups
  get 'groups/:id/new_member/', to: 'groups#new_member', as: "new_member"
  post '/groups/:id/new_member/', to: 'groups#create_member', as: "create_member"
  post '/groups/destroy_member/:id', to: 'groups#destroy_member', as: "destroy_member"
  post '/groups/:id/update_member/', to:'groups#update_member', as: "update_member" 

  resources :user_classes, except:[:destroy]
  get '/user_classes/:id/new_subclass/', to: 'user_classes#new_subclass', as: "new_subclass"
  post '/user_classes/:id/new_subclass/', to: 'user_classes#create_subclass', as: "create_subclass"
  get '/user_classes/:id/edit_subclass/', to:'user_classes#edit_subclass', as: "edit_subclass"
  post '/user_classes/:id/edit_subclass/', to:'user_classes#update_subclass', as: "update_subclass"
  
  resources :sessions, only:[:new, :create, :destroy]
  get "/login", to: "sessions#new", as: "login"
  post "/logout", to: "sessions#destroy", as: "logout"
  root 'sessions#new'

  resources :users
  resources :comments
  get 'comments/:id/show_comment/', to: 'comments#show_comment', as: "show_comment"
  get 'comments/:id/edit_comment/', to:'comments#edit_comment', as: "edit"

  resources :skills
  
  resources :tasks
  get '/tasks/:id/partipar', to: 'tasks#assign_new', as: 'new_assign'
  get '/tasks/:id/comentarios', to: 'tasks#show_comments', as: 'show_comments'
  post '/tasks/:id/partipar', to: 'tasks#assign', as: 'create_assign'
  post '/tasks/:id/increase_xp', to: 'tasks#increase_xp', as: 'increase_xp'
  post '/tasks/:id/increase_time', to: 'tasks#increase_time', as: 'increase_time'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :task
end

app/models/group.rb
class Group < ApplicationRecord
    has_many :members
    has_many :users

    belongs_to :people_tasks, :optional => true
end

app/models/level.rb
class Level < ApplicationRecord
end

app/models/member.rb
class Member < ApplicationRecord
  belongs_to :user
  belongs_to :group
end

app/models/nivel.rb
class Nivel < ApplicationRecord
end

app/models/people_task.rb
class PeopleTask < ApplicationRecord
  belongs_to :user, :optional => true
  belongs_to :group, :optional => true
  belongs_to :task
end

app/models/shop_item.rb
class ShopItem < ApplicationRecord
end

app/models/skill.rb
class Skill < ApplicationRecord
    belongs_to :user_subclass
    belongs_to :user_class
end

app/models/task.rb
class Task < ApplicationRecord
    has_many :people_tasks
    has_many :users
    has_many :groups
    has_many :comments
end

app/models/task_class.rb
class TaskClass < ApplicationRecord
  has_one :user_class
end

app/models/user.rb
class User < ApplicationRecord
  authenticates_with_sorcery!
  validates :password, confirmation: true, if: -> { new_record? || changes[:crypted_password] }
  validates :password_confirmation, presence: true, if: -> { new_record? || changes[:crypted_password] }


  #belongs_to :member, optional: true
  
  has_one :member
  belongs_to :group, :optional => true
  belongs_to :user_class

  has_many :comments
  
  
  has_many :people_tasks
  belongs_to :tasks, :optional => true

  has_many :user_skills
  has_many :skills

end

app/models/user_class.rb
class UserClass < ApplicationRecord
    has_many :user_subclasses
    has_many :users
    has_many :skills
end

app/models/user_skill.rb
class UserSkill < ApplicationRecord
  belongs_to :user
  belongs_to :skill
end

app/models/user_subclass.rb
class UserSubclass < ApplicationRecord
  belongs_to :user_class
  has_many :skills
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  def new
    @group = Group.new()
    @member = Member.new()
  end

  def create
    @group = Group.new(group_params)
    @member = Member.new()
    @member.user_id = current_user.id
    @member.lider = 'SIM'
    @member.status = 'ATIVO'
    if @group.save
      @member.group_id = @group.id
      if @member.save
        redirect_to group_path(@group)
      end
    else
      render 'new'
    end
  end

  def index
    @groups = Group.all
  end

  def show
    @group = Group.find(params[:id])
    if current_user and current_user.member
      @member = User.find(current_user.id).member
    end
  end

  def edit
    @group = Group.find(params[:id])
    
  end

  def update
    @group = Group.find(params[:id])
    if @group.update(group_params)
      redirect_to groups_path
    else
      render 'edit'
    end
  end

  def destroy
    @group = Group.find(params[:id])
    @group.members.each do |member|
      member.destroy
    end
    @group.destroy
    redirect_to groups_path
  end

  def new_member
    @member = Member.new()
    @users = User.all.collect{|user|[user.nome, user.id]}
  end

  def create_member
    @member = Member.new(user_id:params[:user_id], lider:params[:lider], group_id: params[:id])
    @users = User.all.collect{|user|[user.nome, user.id]}
    @member.status = "PENDENTE"
    if @member.save
      redirect_to group_path(@member.group)
    else
      render 'new_member'
    end
  end

  def edit_member
    @member = Member.find(params[:id])
  end

  def update_member
    @member = Member.find(params[:id])
    @member.update(status:params[:button])
    redirect_to user_path(@member.user)
  end

  def destroy_member
    @member = Member.find(params[:id])
    @group = @member.group
    @member.destroy
    redirect_to group_path(@group)
  end

  private
    def group_params
      params.require(:group).permit(:nome, :validade)
    end

    def member_params
      params.permit(:user_id, :lider, :id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def flash_message
        messages = ""
        [:notice, :info, :warning, :error].each {|type|
            if flash[type]
              messages += "<p class=\"#{type}\">#{flash[type]}</p>"
            end
        }
      
        messages
    end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/skills_helper.rb
module SkillsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/groups/_form-group-edit.html.erb
<%= render "users/users-navbar" %>
<div class="container w-25">
    <h1>Editar Grupo</h1>
    <%= form_with model: @group, local: true do |f|%>
        <div class="form-group">
            <%= f.label :nome, "Nome" %>
            <%= f.text_field :nome, placeholder: "Digite o novo nome do grupo", class: "form-control" %>
        </div>
        <div class="form-group">
            <%= f.label :validade, "Validade" %>
            <%= f.date_field :validade, class: "form-control" %>
        </div>
        <%= f.submit "Editar", class: "btn btn-success" %>
    <% end %>
    </div>
</div>

app/views/groups/_form-group-new.html.erb
<%= render "users/users-navbar" %>
<div class="container w-25"> 
    <h1>Criar Grupo</h1>
    <%= form_with model: @group, local: true do |f|%>
        <div class="form-group">
            <%= f.label :nome, "Nome" %>
            <%= f.text_field :nome, placeholder: "Digite o nome do grupo",class: "form-control" %>
        </div>
        <div class="form-group">
            <%= f.label :validade, "Validade" %>
            <%= f.date_field :validade, class: "form-control" %>
        </div>
        <%= f.submit "Criar", class: "btn btn-success"%>
    <% end %>
</div>

        

app/views/groups/edit.html.erb
<% if current_user %>
    <% if current_user.member and current_user.member.lider %>
        <%= render 'form-group-edit' %>
    <% else %>
        <h1 class="error">Você não tem permissão para editar este grupo!</h1>
        <div class="buttons">
            <button class="link"><%= link_to "Voltar", groups_path %></button>
        </div>
    <% end %>
<% else %>
    <h1 class="error">Usuário não autenticado!</h1>
    <div class="buttons">
        <button class="link"><%= link_to "Voltar", groups_path %></button>
        <button class="link"><%= link_to "Fazer Login", new_session_path %></button>
    </div>
<% end %>

app/views/groups/index.html.erb
<%= render "users/users-navbar" %>
<div class="container">
    <div class="row justify-content-center">
        <h1>Grupos</h1>
        <table class="table">
            <tr>
                <th>ID</th>
                <th>Nome</th>
                <th>Validade</th>
                <th colspan="3">Ações</th>
            </tr>
            <% @groups.each do |u|%>
                <tr>
                    <td><%= u.id %></td>
                    <td><%= u.nome %></td>
                    <td><%= u.validade%></td>
                    <td class="link"><%= link_to "Exibir", action: "show", id: u %></td>
                    <td class="link"><%= link_to "Editar", edit_group_path(u) %></td>
                    <td class="link"><%= link_to "Destruir", u, method: :delete %></td>
                </tr>
            <%end%>
        </table>
        <%= link_to "Novo Grupo", {action: "new"}, class: "btn btn-primary" %>
    </div>
</div>

app/views/groups/new.html.erb
<% if current_user %>
    <% if !current_user.member ||current_user.member.status == "RECUSADO" %>
        <%= render 'form-group-new' %>
    <% else %>
        <div class="container">
            <h1 class="error">Você já faz parte de um grupo</h1>
            <div class="row justify-content-center">
                <%= link_to "Voltar", groups_path, class: "btn btn-secondary" %>
            </div>
        </div>
    <% end %>
<% else %>
    <div class="container">
        <h1 class="error">Usuário não autenticado!</h1>
        <div class="row justify-content-center">
            <%= link_to "Voltar", groups_path, class:"btn btn-secondary mr-5" %>
            <%= link_to "Fazer Login", new_session_path, class: "btn btn-primary" %>
        </div>
    </div>
<% end %>
        

app/views/groups/new_member.html.erb
<div class="container w-25">
    <h1>Adicionar Membro</h1>
    <%= form_with model: @members, url: create_member_path,local: true do |f| %>
        <div class="form-group">
            <%= f.label :user_id, "Usuário"%>
            <%= f.select :user_id, @users, class: "form-control" %>
        </div>
        <div class="form-group">
            <%= f.label :lider, "Lider" %>
            <%= f.select(:lider, options_for_select([['SIM'], ['NÃO']])) %>
        </div>
        <%= f.submit "Confirmar", class: "btn btn-success"%>
    <%end%>
</div>

app/views/groups/show.html.erb
<%= render 'users/users-navbar' %>
<div class="container">
    <div class="row justify-content-center">
        <h1><%= @group.nome %></h1>
        <table class="table">
            <tr>
                <th>ID</th>
                <th>MEMBROS</th>
                <th>STATUS</th>
                <th>LIDER</th>
                <% if @member %>
                    <% if @member.lider == "SIM" and @member.group.id == @group.id and @member.status == "ATIVO" %>
                        <th>AÇÃO</th>
                    <% end %>
                <% end %>
            </tr>
            <% @group.members.each do |member| %>
                <tr>
                    <td><%= member.id %></td>
                    <td><%= member.user.nome %></td>
                    <td><%= member.status %></td>
                    <td><%= member.lider %></td>
                    <% if @member %>
                        <% if @member.lider == "SIM" and @member.group.id == @group.id and @member.status == "ATIVO" %>
                            <td class="link"><%= link_to "Excluir", destroy_member_path(member.id), method: :post%></td>
                        <% end %>
                    <% end %>
                </tr>
            <% end %>
        </table>
        <% if @member %>
            <% if @member.lider == "SIM" and @member.group.id == @group.id %>
                <%= link_to "Adicionar Membro", new_member_path, class: "btn btn-dark"%>
            <% end %>
        <% end%>
        <%= link_to "Início", groups_path, class: "btn btn-dark"%></button>
    </div>
</div>