config/routes.rb
Rails.application.routes.draw do
  resources :groups
  get 'groups/:id/new_member/', to: 'groups#new_member', as: "new_member"
  post '/groups/:id/new_member/', to: 'groups#create_member', as: "create_member"
  post '/groups/destroy_member/:id', to: 'groups#destroy_member', as: "destroy_member"
  post '/groups/:id/update_member/', to:'groups#update_member', as: "update_member" 

  resources :user_classes, except:[:destroy]
  get '/user_classes/:id/new_subclass/', to: 'user_classes#new_subclass', as: "new_subclass"
  post '/user_classes/:id/new_subclass/', to: 'user_classes#create_subclass', as: "create_subclass"
  get '/user_classes/:id/edit_subclass/', to:'user_classes#edit_subclass', as: "edit_subclass"
  post '/user_classes/:id/edit_subclass/', to:'user_classes#update_subclass', as: "update_subclass"
  
  resources :sessions, only:[:new, :create, :destroy]
  get "/login", to: "sessions#new", as: "login"
  post "/logout", to: "sessions#destroy", as: "logout"
  root 'sessions#new'

  resources :users
  resources :comments
  get 'comments/:id/show_comment/', to: 'comments#show_comment', as: "show_comment"
  get 'comments/:id/edit_comment/', to:'comments#edit_comment', as: "edit"

  resources :skills
  
  resources :tasks
  get '/tasks/:id/partipar', to: 'tasks#assign_new', as: 'new_assign'
  get '/tasks/:id/comentarios', to: 'tasks#show_comments', as: 'show_comments'
  post '/tasks/:id/partipar', to: 'tasks#assign', as: 'create_assign'
  post '/tasks/:id/increase_xp', to: 'tasks#increase_xp', as: 'increase_xp'
  post '/tasks/:id/increase_time', to: 'tasks#increase_time', as: 'increase_time'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :task
end

app/models/group.rb
class Group < ApplicationRecord
    has_many :members
    has_many :users

    belongs_to :people_tasks, :optional => true
end

app/models/level.rb
class Level < ApplicationRecord
end

app/models/member.rb
class Member < ApplicationRecord
  belongs_to :user
  belongs_to :group
end

app/models/nivel.rb
class Nivel < ApplicationRecord
end

app/models/people_task.rb
class PeopleTask < ApplicationRecord
  belongs_to :user, :optional => true
  belongs_to :group, :optional => true
  belongs_to :task
end

app/models/shop_item.rb
class ShopItem < ApplicationRecord
end

app/models/skill.rb
class Skill < ApplicationRecord
    belongs_to :user_subclass
    belongs_to :user_class
end

app/models/task.rb
class Task < ApplicationRecord
    has_many :people_tasks
    has_many :users
    has_many :groups
    has_many :comments
end

app/models/task_class.rb
class TaskClass < ApplicationRecord
  has_one :user_class
end

app/models/user.rb
class User < ApplicationRecord
  authenticates_with_sorcery!
  validates :password, confirmation: true, if: -> { new_record? || changes[:crypted_password] }
  validates :password_confirmation, presence: true, if: -> { new_record? || changes[:crypted_password] }


  #belongs_to :member, optional: true
  
  has_one :member
  belongs_to :group, :optional => true
  belongs_to :user_class

  has_many :comments
  
  
  has_many :people_tasks
  belongs_to :tasks, :optional => true

  has_many :user_skills
  has_many :skills

end

app/models/user_class.rb
class UserClass < ApplicationRecord
    has_many :user_subclasses
    has_many :users
    has_many :skills
end

app/models/user_skill.rb
class UserSkill < ApplicationRecord
  belongs_to :user
  belongs_to :skill
end

app/models/user_subclass.rb
class UserSubclass < ApplicationRecord
  belongs_to :user_class
  has_many :skills
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.order :id
  end

  def show
    @user = User.find(params[:id])
    if @user.member
      if @user.member.status == "ATIVO"
        @status = @user.member.group.nome
      else
        @status = "Não está em um grupo"
      end
    else
      @status = "Não está em um grupo"
    end
  end

  def new
    @user = User.new()
    @userclass = UserClass.all.collect{|userclass|[userclass.nome, userclass.id]}
  end

  def create
    @user = User.new(user_params)
    @userclass = UserClass.all.collect{|userclass|[userclass.nome, userclass.id]}
    @user.qnt_moedas = 15
    @user.level = 1

    if @user.save
      redirect_to user_path(@user)
    else
      render 'new'
    end
  end

  def update
    @user = User.find(params[:id])
    @userclass = UserClass.all.collect{|userclass|[userclass.nome, userclass.id]}
    if @user.update(user_params)
      redirect_to user_path(@user)
    else
      render 'edit'
    end
  end

  def edit
    @user = User.find(params[:id])
    @userclass = UserClass.all.collect{|user_class|[user_class.nome, user_class.id]}
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to action: "index"
  end
  
  private
  def user_params
    params.require(:user).permit(:nome, :apelido, :email, :data_nascimento, :local_nascimento, :genero, :user_class_id, :group_id, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def flash_message
        messages = ""
        [:notice, :info, :warning, :error].each {|type|
            if flash[type]
              messages += "<p class=\"#{type}\">#{flash[type]}</p>"
            end
        }
      
        messages
    end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/skills_helper.rb
module SkillsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form-users.html.erb
<div class="container w-25">
  <%= form_with model: @user, local: true do |f| %>
      <div class="form-group">
        <%= f.label :nome, "Nome" %>
        <%= f.text_field :nome, placeholder: "Digite seu nome", class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.label :apelido, "Apelido" %>
        <%= f.text_field :apelido, placeholder: "Digite seu apelido", class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.label :email, "Email" %>
        <%= f.text_field :email, placeholder: "Digite seu e-mail", class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.label :data_nascimento, "Data de nascimento" %>
        <%= f.date_field :data_nascimento, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.label :local_nascimento, "Local de nascimento" %>
        <%= f.text_field :local_nascimento, placeholder: "Digite a tua cidade de nascimento", class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.label :genero, "Gênero" %>
        <%= f.select(:genero, options_for_select([['Masculino'], ['Feminino']])) %>
      </div>
      <div class="form-group">
        <%= f.label :user_class_id, "Classe de Jogador" %>
        <%= f.select :user_class_id, @userclass, class: "form-control"%>
      </div>
      <div class="form-group">
        <%= f.label :password, "Senha" %>
        <%= f.password_field :password, placeholder: "Digite sua senha", class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.label :password_confirmation, "Confirme sua Senha" %>
        <%= f.password_field :password_confirmation, placeholder: "Digite novamente sua senha", class: "form-control" %>
      </div>
      
      <%= f.submit "Confirmar", class: "btn btn-success"%>
  <%end%>
</div>

<% @user.errors.full_messages.each do |error| %>
  <p style = "color:red"><%= error %></p>
<% end %>

app/views/users/_users-navbar.html.erb
<nav class= "navbar navbar-dark bg-dark ">
    <div  class="justify-content-start">
        <%= link_to "Usuários", users_path, class: "btn btn-primary" %>
        <%= link_to "Classes", user_classes_path, class: "nav-item btn btn-primary" %> 
        <%= link_to "Grupos", groups_path, class: "btn btn-primary" %>
        <%= link_to "Tarefas", tasks_path, class: "btn btn-primary" %>
    </div>
    <div  class="justify-content-end">
    <%if current_user %>
        <span style="color:#FFF">Olá, <%= current_user.nome %></span>
        <%= link_to "Logout", :logout,method: :post, class: "btn btn-danger ml-3" %>
    <%else%>
        <%= link_to "Login", new_session_path, class: "btn btn-primary" %>
    <%end%>
    </div>
</nav>

app/views/users/edit.html.erb
<% if current_user == @user %>
    <h1>Editar <%= @user.nome %></h1>
    <%= render 'users/form-users' %>
<% else %>
    <div class="container">
        <h1 class="error">Usuário não autenticado!</h1>
        <div class="row justify-content-center">
            <%= link_to "Página inicial", users_path, class:"btn btn-secondary mr-5" %>
            <%= link_to "Fazer Login", new_session_path, class: "btn btn-primary" %>
        </div>
    </div>
<% end %>

app/views/users/index.html.erb
<%= render 'users/users-navbar' %>
<div class="container mt-3">
    <div class="row justify-content-center">
        <h1>Usuários</h1>
        <table class="table">
            <tr>
                <th>ID</th>
                <th>Nome</th>
                <th>Nível</th>
                <th colspan="3">Ações</th>
            </tr>
            <% @users.each do |u|%>
                <tr>
                    <td><%= u.id %></td>
                    <td><%= u.nome %></td>
                    <td><%= u.level %></td>
                    <td class="link"><%= link_to "Exibir", action: "show", id: u %></td>
                    <td class="link"><%= link_to "Destruir", u, method: :delete %></td>
                    <td class="link"><%= link_to "Editar", edit_user_path(u) %></td>
                </tr>
            <%end%>
        </table>
        <%= link_to "Novo usuário", {action: "new"}, class: "btn btn-primary" %>
    </div>
</div>

app/views/users/new.html.erb
<h1>Cadastrar Usuário</h1>
<%= render 'users/form-users' %>

app/views/users/show.html.erb
<%= render 'users/users-navbar' %>
<h1><%= @user.nome %></h1>
<div class="container">
    <ul class="list-group">
        <li class="list-group-item">Nome: <%= @user.nome %></li>
        <li class="list-group-item">Apelido: <%= @user.apelido %></li>
        <li class="list-group-item">E-mail: <%= @user.email %></li>
        <li class="list-group-item">Data de nascimento: <%= @user.data_nascimento %></li>
        <li class="list-group-item">Local de nascimento: <%= @user.local_nascimento %></li>
        <li class="list-group-item">Gênero: <%= @user.genero %></li>
        <li class="list-group-item">Level: <%= @user.level %></li>
        <li class="list-group-item">Classe: <%= @user.user_class.nome %></li>
        <li class="list-group-item">Moedas: <%= @user.qnt_moedas %></li>
        <% if current_user and @user.member and current_user.id == @user.id and (@user.member.status == "PENDENTE") %>
            <li class="list-group-item">Solicitação do Grupo: "<%= @user.member.group.nome %>"
                <%= form_with scope: :member, url: update_member_path(@user.member.id), local: true do |f| %><br>
                    <%= f.button "Aceitar", name: "button", value: "ATIVO", class: "btn btn-success" %>
                    <%= f.button "Recusar", name: "button", value: "RECUSADO", class:"btn btn-danger" %> 
                <% end %>
            </li>              
        <% else %>
            <li class="list-group-item">Grupo: <%= @status%></li>
        <% end %>
        <li class="list-group-item">Criado em: <%= @user.created_at %></li>
        <li class="list-group-item">Atualizado em: <%= @user.updated_at %></li>
    </ul>
    <%= link_to "Início", users_path, class: "btn btn-dark w-100 mb-4 mt-4" %>
</div>