config/routes.rb
Rails.application.routes.draw do
  resources :groups
  get 'groups/:id/new_member/', to: 'groups#new_member', as: "new_member"
  post '/groups/:id/new_member/', to: 'groups#create_member', as: "create_member"
  post '/groups/destroy_member/:id', to: 'groups#destroy_member', as: "destroy_member"
  post '/groups/:id/update_member/', to:'groups#update_member', as: "update_member" 

  resources :user_classes, except:[:destroy]
  get '/user_classes/:id/new_subclass/', to: 'user_classes#new_subclass', as: "new_subclass"
  post '/user_classes/:id/new_subclass/', to: 'user_classes#create_subclass', as: "create_subclass"
  get '/user_classes/:id/edit_subclass/', to:'user_classes#edit_subclass', as: "edit_subclass"
  post '/user_classes/:id/edit_subclass/', to:'user_classes#update_subclass', as: "update_subclass"
  
  resources :sessions, only:[:new, :create, :destroy]
  get "/login", to: "sessions#new", as: "login"
  post "/logout", to: "sessions#destroy", as: "logout"
  root 'sessions#new'

  resources :users
  resources :comments
  get 'comments/:id/show_comment/', to: 'comments#show_comment', as: "show_comment"
  get 'comments/:id/edit_comment/', to:'comments#edit_comment', as: "edit"

  resources :skills
  
  resources :tasks
  get '/tasks/:id/partipar', to: 'tasks#assign_new', as: 'new_assign'
  get '/tasks/:id/comentarios', to: 'tasks#show_comments', as: 'show_comments'
  post '/tasks/:id/partipar', to: 'tasks#assign', as: 'create_assign'
  post '/tasks/:id/increase_xp', to: 'tasks#increase_xp', as: 'increase_xp'
  post '/tasks/:id/increase_time', to: 'tasks#increase_time', as: 'increase_time'
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :task
end

app/models/group.rb
class Group < ApplicationRecord
    has_many :members
    has_many :users

    belongs_to :people_tasks, :optional => true
end

app/models/level.rb
class Level < ApplicationRecord
end

app/models/member.rb
class Member < ApplicationRecord
  belongs_to :user
  belongs_to :group
end

app/models/nivel.rb
class Nivel < ApplicationRecord
end

app/models/people_task.rb
class PeopleTask < ApplicationRecord
  belongs_to :user, :optional => true
  belongs_to :group, :optional => true
  belongs_to :task
end

app/models/shop_item.rb
class ShopItem < ApplicationRecord
end

app/models/skill.rb
class Skill < ApplicationRecord
    belongs_to :user_subclass
    belongs_to :user_class
end

app/models/task.rb
class Task < ApplicationRecord
    has_many :people_tasks
    has_many :users
    has_many :groups
    has_many :comments
end

app/models/task_class.rb
class TaskClass < ApplicationRecord
  has_one :user_class
end

app/models/user.rb
class User < ApplicationRecord
  authenticates_with_sorcery!
  validates :password, confirmation: true, if: -> { new_record? || changes[:crypted_password] }
  validates :password_confirmation, presence: true, if: -> { new_record? || changes[:crypted_password] }


  #belongs_to :member, optional: true
  
  has_one :member
  belongs_to :group, :optional => true
  belongs_to :user_class

  has_many :comments
  
  
  has_many :people_tasks
  belongs_to :tasks, :optional => true

  has_many :user_skills
  has_many :skills

end

app/models/user_class.rb
class UserClass < ApplicationRecord
    has_many :user_subclasses
    has_many :users
    has_many :skills
end

app/models/user_skill.rb
class UserSkill < ApplicationRecord
  belongs_to :user
  belongs_to :skill
end

app/models/user_subclass.rb
class UserSubclass < ApplicationRecord
  belongs_to :user_class
  has_many :skills
end

app/controllers/user_classes_controller.rb
class UserClassesController < ApplicationController
  def new
    @userclass = UserClass.new()
  end

  def create
    @userclass = UserClass.new(nome:params[:user_class][:nome])
    if @userclass.save
      redirect_to user_class_path(@userclass)
    else
      render 'new'
    end
  end

  def edit
    @userclass = UserClass.find(params[:id])
  end

  def update
    @userclass = UserClass.find(params[:id])
    if @userclass.update(nome:params[:user_class][:nome])
      redirect_to user_class_path(@userclass)
    else
      render 'edit'
    end
  end

  def new_subclass
    @subclass = UserSubclass.new()
  end

  def create_subclass
    @subclass = UserSubclass.new(user_class_id:params[:id], nome:params[:nome])
    if @subclass.save
      redirect_to user_class_path(@subclass.user_class)
    else
      render 'new_subclass'
    end
  end

  def edit_subclass
    @subclass = UserSubclass.find(params[:id])
  end

  def update_subclass
    @subclass = UserSubclass.find(params[:id])
    if @subclass.update(nome:params[:nome])
      redirect_to user_class_path(@subclass.user_class)
    else
      render 'edit_subclass'
    end
  end

  def index
    @userclass = UserClass.all
    @skill = Skill.all
  end

  def show
    @userclass = UserClass.find(params[:id])
  end

  private
  
  def class_params
    params.require(:user_class).permit(:nome)
  end

end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/skills_helper.rb
module SkillsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/user_classes_helper.rb
module UserClassesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/user_classes/_form-userclass.html.erb
<div class="container w-25">
  <%= form_with model: @userclass, local: true do |f| %>
    <div class="form-group">
      <%= f.label :nome, "Nome"%>
      <%= f.text_field :nome, class: "form-control" %>
    </div>
    <%= f.submit "Confirmar", class: "btn btn-success"%>
  <%end%>

  <% @userclass.errors.full_messages.each do |error| %>
    <p style = "color:red"><%= error %></p>
  <% end %>
</div>

app/views/user_classes/edit.html.erb
<h1>Editar Classe </h1>
<%=render 'form-userclass'%>

app/views/user_classes/edit_subclass.html.erb
<div class="container w-25">
    <h1>Editar Subclasse </h1>
    <%= form_with model: @usersubclass, url: update_subclass_path,local: true do |f| %>
        <div class="form-group">
            <%= f.label :nome, "Nome"%>
            <%= f.text_field :nome, placeholder: "Digite o nome da Subclasse",class: "form-control"%>
        </div>
        <%= f.submit "Confirmar", class: "btn btn-success"%>
    <%end%>
</div>

app/views/user_classes/index.html.erb
<%= render 'users/users-navbar'%>
<div class="p-3">
    <div class="row justify-content-center">
        <h1>Classes</h1>
        <table class="table">
            <tr>
                <th>ID</th>
                <th>Nome</th>
                <th colspan="3">Ações</th>
            </tr>
            <% @userclass.each do |u|%>
                <tr>
                    <td><%= u.id %></td>
                    <td><%= u.nome %></td>
                    <td class="link"><%= link_to "Exibir", action: "show", id: u %></td>
                    <td class="link"><%= link_to "Editar", edit_user_class_path(u) %></td>
                </tr>
            <%end%>
        </table>
        <%= link_to "Nova classe", {action: "new"}, class: "btn btn-primary" %>
    </div>
</div>
<br>
<div class="p-3">
    <div class="row justify-content-center">
        <h1>Habilidades</h1>
        <table class="table">
            <tr>
                <th>ID</th>
                <th>Nome</th>
                <th colspan="3">Ações</th>
            </tr>
            <% @skill.each do |s|%>
                <tr>
                    <td><%= s.id %></td>
                    <td><%= s.nome %></td>
                    <td class="link"><%= link_to "Editar", edit_skill_path(s) %></td>
                    <td class="link"><%= link_to "Excluir", s, method: :delete %></td>
                </tr>
            <%end%>
        </table>
        <%= link_to "Nova Habilidade", new_skill_path, class: "btn btn-primary" %>
    </div>
</div>

app/views/user_classes/new.html.erb
<h1>Criar Classe </h1>
<%=render 'form-userclass'%>

app/views/user_classes/new_subclass.html.erb
<div class="container w-25">
    <h1>Criar Subclasse</h1>
    <%= form_with model: @usersubclass, url: create_subclass_path,local: true do |f| %>
        <div class="form-group">
            <%= f.label :nome, "Nome"%>
            <%= f.text_field :nome, placeholder: "Digite o nome da Subclasse", class: "form-control" %>
        </div>
        <%= f.submit "Confirmar", class: "btn btn-success"%>
    <%end%>
</div>

app/views/user_classes/show.html.erb
<%= render 'users/users-navbar'%>
<div class="container mt-3">
    <div class="row justify-content-center">
    <h1><%= @userclass.nome %></h1>
        <table class="table">
            <tr>
                <th>ID</th>
                <th>Subclasses</th>
                <th colspan="3">Ações</th>
            </tr>
            <% @userclass.user_subclasses.each do |u|%>
                <tr>
                    <td><%= u.id %></td>
                    <td><%= u.nome %></td>
                    <td class="link"><%= link_to "Editar", edit_subclass_path(u) %></td>
                </tr>
            <%end%>
        </table>
        <button class="btn btn-primary"><%= link_to "Nova Subclasse",  new_subclass_path(@userclass) %></button>
        <button class="btn btn-dark ml-5"><%= link_to "Início", user_classes_path %></button>
    </div>
</div>